from pymongo import typings
{
    "_id": typings.ObjectId,
    "timestamp": str,
    "customer_id": str,
    "bot_name": str,
    "symbol": str,
    "side": str,
    "type": str,
    "quantity": float,
    "price": float,
    "value": float,
    "balance_symbol1": float,
    "balance_symbol2": float,
    "value_symbol1": float,
    "value_symbol2": float,
    "value_sum": float,
    "percent": float,
    "target_value_symbol1": float,
    "target_value_symbol2": float,
}